
from django.urls import include, path
from home import views

urlpatterns = [
    path('',views.index),
    path('shop/',views.shop),
    path('shop-detail/<id>',views.shopdetail),
    path('contact/',views.contact),
    path('login/',views.Login),
    path('check_login/',views.checklogin),
    path('dashboard/',views.dashboard),
    path('catogary/',views.catogary),
    path('catogaryedit/<id>',views.catogaryedit),
    path('catogarydelete/<id>',views.catogarydelete),
    path('addcatogary/',views.addcatogary),
    path('addcatogaryhandle/',views.addcatogaryhandle),
    path('handleedit/<id>',views.handleedit),
    path('brands/',views.brands),
    path('addbrand/',views.addbrand),
    path('addbrandhandle/',views.addbrandhandle),
    path('brandedit/<id>',views.brandedit),
    path('brandedithandle/<id>',views.brandedithandle),
    path('branddelete/<id>',views.branddelete),
    path('products/',views.products),
    path('addproduct/',views.addproduct),
    path('addproducthandle/',views.addproducthandle),
    path('productedit/<id>',views.productedit),
    path('productedithandle/<id>',views.productedithandle),
    path('productdelete/<id>',views.productdelete),
    path('logout/',views.Logout),
    path('addenquries/',views.addenquries),
    path('low_to_high/',views.low_to_high),
    path('high_to_low/',views.high_to_low),
    path('productsearch/',views.productsearch),
    path('vegsearch/',views.vegsearch),
    path('fruitssearch/',views.fruitssearch),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.view_cart, name='view_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('paymenthandler/',views.paymenthandler),
    path('view_cart/',views.view_cart),
    path('removecart/<id>',views.removecart),
    path('payment_success/',views.ordersuccess),

]
