# Generated by Django 5.2.7 on 2025-11-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catogary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catogaryname', models.CharField(max_length=100, null=True)),
                ('catogaryimage', models.ImageField(null=True, upload_to='media')),
                ('catogarystatus', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
