# Generated by Django 5.2.7 on 2025-11-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='catogary',
            new_name='catogarytable',
        ),
    ]
