# Generated by Django 5.2.7 on 2025-11-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_catogary_catogarytable'),
    ]

    operations = [
        migrations.CreateModel(
            name='brandstable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=100, null=True)),
                ('brandimage', models.ImageField(null=True, upload_to='media')),
                ('brandstatus', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
