# Generated by Django 5.2.7 on 2025-11-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_brandstable'),
    ]

    operations = [
        migrations.CreateModel(
            name='productstable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('description', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
