# Generated by Django 5.2.7 on 2025-11-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_productstable'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstable',
            name='brand',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
