# Generated by Django 5.2.7 on 2025-11-05 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_productstable_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstable',
            name='catogary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.catogarytable'),
        ),
        migrations.AddField(
            model_name='productstable',
            name='current_stock',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='productstable',
            name='open_stock',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='productstable',
            name='orginal_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='productstable',
            name='our_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='productstable',
            name='tax_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productstable',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.brandstable'),
        ),
    ]
