# Generated by Django 5.2.7 on 2025-11-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_productstable_catogary_productstable_current_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquiries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('message', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
