# Generated by Django 5.2.7 on 2025-11-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_cart_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderupdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField(null=True)),
                ('updatedesc', models.CharField(max_length=100, null=100)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='oid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
