# Generated by Django 5.2.7 on 2025-11-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_orderupdates_order_oid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdates',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderupdates',
            name='paymentid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
